### ISSUE TITLE
renaming error

### ISSUE THREAD

**Issue by Originalas** [viktor02/picoInstaller#1]
Renaming gives error 

`C:\Program Files\Python36\picoinstaller>picoinstaller
2023-11-04 19:25:14,816 - root - INFO - Starting app
2023-11-04 19:25:14,816 - root - INFO - Starting adb daemon
adb server version (39) doesn't match this client (41); killing...
* daemon started successfully
2023-11-04 19:25:18,267 - PyQt5.uic.uiparser - DEBUG - uiname is MainWindow
2023-11-04 19:25:18,268 - PyQt5.uic.uiparser - DEBUG - toplevel widget is Ui
2023-11-04 19:25:18,268 - PyQt5.uic.properties - DEBUG - setting property geometry
2023-11-04 19:25:18,268 - PyQt5.uic.properties - DEBUG - setting property acceptDrops
2023-11-04 19:25:18,268 - PyQt5.uic.properties - DEBUG - setting property windowTitle
2023-11-04 19:25:18,268 - PyQt5.uic.properties - DEBUG - setting property windowIcon
2023-11-04 19:25:18,429 - PyQt5.uic.properties - DEBUG - setting property tabShape
2023-11-04 19:25:18,429 - PyQt5.uic.uiparser - DEBUG - push Ui MainWindow
2023-11-04 19:25:18,429 - PyQt5.uic.properties - DEBUG - setting property acceptDrops
2023-11-04 19:25:18,429 - PyQt5.uic.uiparser - DEBUG - push QWidget centralwidget
2023-11-04 19:25:18,429 - PyQt5.uic.properties - DEBUG - setting property pyuicMargins
2023-11-04 19:25:18,429 - PyQt5.uic.uiparser - DEBUG - push QGridLayout gridLayout
2023-11-04 19:25:18,429 - PyQt5.uic.uiparser - DEBUG - push QVBoxLayout verticalLayout
2023-11-04 19:25:18,430 - PyQt5.uic.properties - DEBUG - setting property acceptDrops
2023-11-04 19:25:18,430 - PyQt5.uic.properties - DEBUG - setting property currentIndex
2023-11-04 19:25:18,430 - PyQt5.uic.uiparser - DEBUG - push QTabWidget tabWidget
2023-11-04 19:25:18,430 - PyQt5.uic.uiparser - DEBUG - push QWidget tab
2023-11-04 19:25:18,430 - PyQt5.uic.uiparser - DEBUG - push QGridLayout gridLayout_2
2023-11-04 19:25:18,430 - PyQt5.uic.uiparser - DEBUG - push QVBoxLayout verticalLayout_2
2023-11-04 19:25:18,430 - PyQt5.uic.properties - DEBUG - setting property font
2023-11-04 19:25:18,431 - PyQt5.uic.properties - DEBUG - setting property styleSheet
2023-11-04 19:25:18,431 - PyQt5.uic.properties - DEBUG - setting property text
2023-11-04 19:25:18,431 - PyQt5.uic.properties - DEBUG - setting property alignment
2023-11-04 19:25:18,432 - PyQt5.uic.uiparser - DEBUG - push QLabel labelDrag
2023-11-04 19:25:18,432 - PyQt5.uic.uiparser - DEBUG - pop widget QLabel labelDrag
2023-11-04 19:25:18,432 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432F880>
2023-11-04 19:25:18,432 - PyQt5.uic.properties - DEBUG - setting property text
2023-11-04 19:25:18,432 - PyQt5.uic.uiparser - DEBUG - push QCheckBox checkBoxRenamePackage
2023-11-04 19:25:18,432 - PyQt5.uic.uiparser - DEBUG - pop widget QCheckBox checkBoxRenamePackage
2023-11-04 19:25:18,432 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432F880>
2023-11-04 19:25:18,432 - PyQt5.uic.properties - DEBUG - setting property enabled
2023-11-04 19:25:18,432 - PyQt5.uic.properties - DEBUG - setting property text
2023-11-04 19:25:18,432 - PyQt5.uic.uiparser - DEBUG - push QPushButton installButton
2023-11-04 19:25:18,433 - PyQt5.uic.uiparser - DEBUG - pop widget QPushButton installButton
2023-11-04 19:25:18,433 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432F880>
2023-11-04 19:25:18,433 - PyQt5.uic.uiparser - DEBUG - pop layout QVBoxLayout verticalLayout_2
2023-11-04 19:25:18,433 - PyQt5.uic.uiparser - DEBUG - pop layout QGridLayout gridLayout_2
2023-11-04 19:25:18,433 - PyQt5.uic.uiparser - DEBUG - pop widget QWidget tab
2023-11-04 19:25:18,433 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QTabWidget object at 0x000001C63432F7F0>
2023-11-04 19:25:18,540 - PyQt5.uic.uiparser - DEBUG - push QWidget tab_2
2023-11-04 19:25:18,541 - PyQt5.uic.uiparser - DEBUG - push QGridLayout gridLayout_4
2023-11-04 19:25:18,541 - PyQt5.uic.uiparser - DEBUG - push QVBoxLayout verticalLayout_4
2023-11-04 19:25:18,542 - PyQt5.uic.uiparser - DEBUG - push QListWidget listPackages
2023-11-04 19:25:18,542 - PyQt5.uic.uiparser - DEBUG - pop widget QListWidget listPackages
2023-11-04 19:25:18,542 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432FBE0>
2023-11-04 19:25:18,542 - PyQt5.uic.properties - DEBUG - setting property text
2023-11-04 19:25:18,542 - PyQt5.uic.uiparser - DEBUG - push QPushButton deleteButton
2023-11-04 19:25:18,543 - PyQt5.uic.uiparser - DEBUG - pop widget QPushButton deleteButton
2023-11-04 19:25:18,543 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432FBE0>
2023-11-04 19:25:18,543 - PyQt5.uic.uiparser - DEBUG - pop layout QVBoxLayout verticalLayout_4
2023-11-04 19:25:18,543 - PyQt5.uic.uiparser - DEBUG - pop layout QGridLayout gridLayout_4
2023-11-04 19:25:18,543 - PyQt5.uic.uiparser - DEBUG - pop widget QWidget tab_2
2023-11-04 19:25:18,543 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QTabWidget object at 0x000001C63432F7F0>
2023-11-04 19:25:18,543 - PyQt5.uic.uiparser - DEBUG - push QWidget tab_3
2023-11-04 19:25:18,543 - PyQt5.uic.uiparser - DEBUG - push QGridLayout gridLayout_6
2023-11-04 19:25:18,543 - PyQt5.uic.uiparser - DEBUG - push QVBoxLayout verticalLayout_5
2023-11-04 19:25:18,544 - PyQt5.uic.uiparser - DEBUG - push QPlainTextEdit ShellOutput
2023-11-04 19:25:18,544 - PyQt5.uic.uiparser - DEBUG - pop widget QPlainTextEdit ShellOutput
2023-11-04 19:25:18,544 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432FEB0>
2023-11-04 19:25:18,544 - PyQt5.uic.uiparser - DEBUG - pop layout QVBoxLayout verticalLayout_5
2023-11-04 19:25:18,544 - PyQt5.uic.uiparser - DEBUG - push QLineEdit ShellInput
2023-11-04 19:25:18,544 - PyQt5.uic.uiparser - DEBUG - pop widget QLineEdit ShellInput
2023-11-04 19:25:18,544 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432FEB0>
2023-11-04 19:25:18,545 - PyQt5.uic.properties - DEBUG - setting property text
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - push QLabel label
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - pop widget QLabel label
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432FEB0>
2023-11-04 19:25:18,545 - PyQt5.uic.properties - DEBUG - setting property text
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - push QPushButton SendCommandButton
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - pop widget QPushButton SendCommandButton
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432FEB0>
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - pop layout QGridLayout gridLayout_6
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - pop widget QWidget tab_3
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QTabWidget object at 0x000001C63432F7F0>
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - pop widget QTabWidget tabWidget
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - new topwidget <PyQt5.QtWidgets.QWidget object at 0x000001C63432F640>
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - pop layout QVBoxLayout verticalLayout
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - pop layout QGridLayout gridLayout
2023-11-04 19:25:18,545 - PyQt5.uic.uiparser - DEBUG - pop widget QWidget centralwidget
2023-11-04 19:25:18,546 - PyQt5.uic.uiparser - DEBUG - new topwidget <__main__.Ui object at 0x000001C63432EEF0>
2023-11-04 19:25:18,547 - PyQt5.uic.properties - DEBUG - setting property geometry
2023-11-04 19:25:18,547 - PyQt5.uic.uiparser - DEBUG - push QMenuBar menubar
2023-11-04 19:25:18,547 - PyQt5.uic.uiparser - DEBUG - pop widget QMenuBar menubar
2023-11-04 19:25:18,547 - PyQt5.uic.uiparser - DEBUG - new topwidget <__main__.Ui object at 0x000001C63432EEF0>
2023-11-04 19:25:18,548 - PyQt5.uic.uiparser - DEBUG - push QStatusBar statusbar
2023-11-04 19:25:18,548 - PyQt5.uic.uiparser - DEBUG - pop widget QStatusBar statusbar
2023-11-04 19:25:18,548 - PyQt5.uic.uiparser - DEBUG - new topwidget <__main__.Ui object at 0x000001C63432EEF0>
2023-11-04 19:25:18,548 - PyQt5.uic.uiparser - DEBUG - pop widget Ui MainWindow
2023-11-04 19:25:18,548 - PyQt5.uic.uiparser - DEBUG - new topwidget None
2023-11-04 19:25:36,176 - picoInstaller.model - INFO - Generating new key
Traceback (most recent call last):
  File "picoInstaller\model.py", line 96, in run
    self._handle_apk(model)
  File "picoInstaller\model.py", line 120, in _handle_apk
    new_apk = self._rename_package(self.file_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "picoInstaller\model.py", line 170, in _rename_package
    _, new_apk = renamer.rename_package()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "picoInstaller\model.py", line 277, in rename_package
    keystore_file, keystore_password, keystore_alias, key_password = self.generate_key()
                                                                     ^^^^^^^^^^^^^^^^^^^
  File "picoInstaller\model.py", line 231, in generate_key
    subprocess.run(
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by viktor02** [comment]
Hi, sorry for delay, this errors means it cannot find `keytool` program, which is must be when you install java jre/jdk. If java already installed, but error is the same, check the PATH env variable
